apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digiby-ingress
spec:
  tls:
    - hosts:
        - digiby.predictivemovement.se
      secretName: digiby-prod-tls
  rules:
    - host: digiby.predictivemovement.se
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 4000
