apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: digiby
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: digiby
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: iteam1337/digiby-backend
          resources:
            requests:
              memory: "0.25Gi"
              cpu: "0.5"
            limits:
              cpu: "1"
              memory: "0.25Gi"
          ports:
            - containerPort: 4000
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: digiby-secret-key-base
                  key: secret-key-base

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: digiby
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - digiby.iteam.services
        - digiby.predictivemovement.se
      secretName: digiby-stage-tls
  rules:
    - host: digiby.predictivemovement.se
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 4000
    - host: digiby.iteam.services
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 4000
